jobs:
- job: CleanResources
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@4
    displayName: Deleting Azure Resources
    inputs:
      azureSubscription: "${{ parameters.serviceConnection }}"
      ScriptPath: '$(Build.SourcesDirectory)/$(infraScriptPath)/Cleanup-Resources.ps1' 
      ScriptArguments: '-resourceGroups "$(resourceGroupNamesForCleanup)"'
      azurePowerShellVersion: LatestVersion


 


              

 