steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Application Insights - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/ApplicationInsights/deploy.json'
     overrideParameters: '-webappappinsightname "${{ parameters.webappappinsightname }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Application Insights webappappinsightname
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.webappappinsightname }}"'
     azurePowerShellVersion: LatestVersion
