steps:
- ${{ each keyvaultsecret in parameters.keyvaultSecrets }}:
  - task: AzurePowerShell@4
    displayName: Get KV Access Policy For Service Connection
    inputs:
      azureSubscription: "${{ parameters.azureSubscriptionName }}"
      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Get-KeyVaultAccessPolicies.ps1'
      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}" -keyVaultName "${{ parameters.keyVaultName }}"'
      azurePowerShellVersion: LatestVersion

  - task: AzureResourceGroupDeployment@2
    displayName: Create Key Vault - ARM
    inputs:
      azureSubscription: "${{ parameters.azureSubscriptionName }}"
      resourceGroupName: "${{ parameters.resourceGroupName }}"
      location: "${{ parameters.deployLocation }}"
      csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Key Vault/deploy.json'
      overrideParameters: '-accessPolicies "$(Infra.KeyVault.AccessPolicies)" -keyVaultName "${{ parameters.keyVaultName }}" -skuName "${{parameters.skuName}}" -secretName "${{ keyvaultsecret.secretName }}" -secretValue "${{ keyvaultsecret.secretValue }}"'
  
  - task: AzurePowerShell@4
    displayName: Add tags to key vault
    inputs:
      azureSubscription: "${{ parameters.azureSubscriptionName }}"
      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
      ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.keyVaultName }}"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Set KV Access Policy For Service Connection
    inputs:
      azureSubscription: "${{ parameters.azureSubscriptionName }}"
      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Set-KeyVault-AccessPolicy.ps1'
      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}" -keyVaultName "${{ parameters.keyVaultName }}"'
      azurePowerShellVersion: LatestVersion


