 steps:
     - ${{ each databaseName in parameters.sqldatabases }}:
         - task: AzureResourceGroupDeployment@2
           displayName: Sql Database - ${{ databaseName }} - ARM
           inputs:
             azureSubscription: "${{ parameters.azureSubscriptionName }}"
             resourceGroupName: "${{ parameters.resourceGroupName }}"
             location: "${{ parameters.deployLocation }}"
             csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Sql Database/deploy.json'
             overrideParameters: '-sqlServerName "${{ parameters.sqlServerName }}" -skutier "${{ parameters.sqlDbSkuTier }}" -databaseName "${{ databaseName }}" ' # -sqlElasticPoolName "${{ parameters.sqlElasticPoolName }}"
             deploymentOutputs: armOut

         - task: AzurePowerShell@4
           displayName: Add tags to Sql Database - ${{ databaseName }}
           inputs:
             azureSubscription: "${{ parameters.azureSubscriptionName }}"
             ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
             ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ databaseName }}"'
             azurePowerShellVersion: LatestVersion