steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Storage Account - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Storage Account/deploy.json'
     overrideParameters: '-storageAccountType "${{ parameters.storageAccountType }}" -storageAccountName "${{ parameters.storageAccountName }}"  -storageQueueName "${{ parameters.storageQueueName }}" '
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Storage Account
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.storageAccountName }}"'
     azurePowerShellVersion: LatestVersion
